apiVersion: v1
appVersion: "7.0.0.GA"
description: A Helm chart for Activiti Cloud Connector Quickstart
icon: https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png
name: REPLACE_ME_APP_NAME
version: 0.1.0-SNAPSHOT
